import type { Category, Product, Zone } from './types';
import { packageSize as inferPackageSize } from './shopping';

export const zones: Zone[] = [
  {
    id: 'vegetables',
    name: '蔬菜区',
    code: 'A',
    color: '#456537',
    tint: '#e7eddf',
    location: { x: 6, y: 9 },
    rect: { x: 2, y: 2, w: 8, h: 6 },
  },
  {
    id: 'fruit',
    name: '水果区',
    code: 'B',
    color: '#805b26',
    tint: '#f3e7d5',
    location: { x: 11, y: 13 },
    rect: { x: 2, y: 11, w: 8, h: 5 },
  },
  {
    id: 'seafood',
    name: '水产区',
    code: 'C',
    color: '#376770',
    tint: '#dcebec',
    location: { x: 20, y: 5 },
    rect: { x: 21, y: 2, w: 9, h: 6 },
  },
  {
    id: 'meat',
    name: '肉禽区',
    code: 'D',
    color: '#8f504a',
    tint: '#f2e2df',
    location: { x: 20, y: 12 },
    rect: { x: 21, y: 10, w: 9, h: 5 },
  },
  {
    id: 'dairy',
    name: '乳品区',
    code: 'E',
    color: '#536488',
    tint: '#e4e8f1',
    location: { x: 20, y: 19 },
    rect: { x: 21, y: 17, w: 9, h: 4 },
  },
  {
    id: 'bakery',
    name: '烘焙区',
    code: 'F',
    color: '#79593b',
    tint: '#eee2d5',
    location: { x: 11, y: 20 },
    rect: { x: 2, y: 18, w: 8, h: 4 },
  },
  {
    id: 'pantry',
    name: '粮油区',
    code: 'G',
    color: '#67653e',
    tint: '#eae9d9',
    location: { x: 12, y: 14 },
    rect: { x: 13, y: 11, w: 5, h: 6 },
  },
];

export const categoryLabels = Object.fromEntries(zones.map((z) => [z.id, z.name])) as Record<
  Category,
  string
>;
export const entrance = { x: 15, y: 23 };
export const checkout = { x: 19, y: 21 };
export const extraObstacles = [
  { x: 13, y: 3, w: 5, h: 5 },
  { x: 13, y: 20, w: 5, h: 2 },
];
const definitions: [
  string,
  string,
  Category,
  number,
  string,
  string,
  string,
  string[],
  string[],
][] = [
  [
    'spinach',
    '鲜嫩菠菜',
    'vegetables',
    4.8,
    '500g',
    'spinach',
    '叶片鲜嫩，清炒、煮汤都合适',
    ['绿叶蔬菜', '当季'],
    ['菠菜', 'spinach'],
  ],
  [
    'bokchoy',
    '上海青',
    'vegetables',
    3.5,
    '500g',
    'bokchoy',
    '口感清甜，简单清炒就是家常好味',
    ['绿叶蔬菜', '清炒'],
    ['青菜', '小油菜', '油菜', '上海青', 'bok choy'],
  ],
  [
    'lettuce',
    '奶油生菜',
    'vegetables',
    5.9,
    '500g',
    'lettuce',
    '叶片柔嫩，适合沙拉与轻食搭配',
    ['绿叶蔬菜', '沙拉'],
    ['生菜', 'lettuce'],
  ],
  [
    'broccoli',
    '新鲜西兰花',
    'vegetables',
    6.8,
    '500g',
    'broccoli',
    '花球紧实，焯水后凉拌或清炒',
    ['十字花科', '家常'],
    ['西兰花', '西蓝花', 'broccoli'],
  ],
  [
    'tomato',
    '自然熟番茄',
    'vegetables',
    5.5,
    '500g',
    'tomato',
    '酸甜多汁，番茄炒蛋的好搭档',
    ['茄果类', '家常'],
    ['西红柿', '番茄', 'tomato'],
  ],
  [
    'carrot',
    '脆甜胡萝卜',
    'vegetables',
    3.8,
    '500g',
    'carrot',
    '清甜爽脆，炖汤或鲜榨都不错',
    ['根茎类'],
    ['胡萝卜', '红萝卜', 'carrot'],
  ],
  [
    'apple',
    '红富士苹果',
    'fruit',
    8.8,
    '500g',
    'apple',
    '果肉脆甜，日常水果常备之选',
    ['脆甜'],
    ['苹果', 'apple'],
  ],
  [
    'banana',
    '香甜香蕉',
    'fruit',
    4.5,
    '500g',
    'banana',
    '软糯香甜，早餐和加餐都方便',
    ['软糯'],
    ['香蕉', 'banana'],
  ],
  [
    'orange',
    '阳光甜橙',
    'fruit',
    6.9,
    '500g',
    'orange',
    '果香清新，汁水饱满',
    ['多汁'],
    ['橙子', '甜橙', '橙', 'orange'],
  ],
  [
    'strawberry',
    '红颜草莓',
    'fruit',
    19.8,
    '250g',
    'strawberry',
    '果香浓郁，适合直接品尝',
    ['鲜甜'],
    ['草莓', 'strawberry'],
  ],
  [
    'seabass',
    '鲜活鲈鱼',
    'seafood',
    22.8,
    '500g',
    'fish',
    '肉质细嫩，适合葱姜清蒸',
    ['鱼类', '清蒸'],
    ['鲈鱼', 'bass'],
  ],
  [
    'salmon',
    '挪威三文鱼',
    'seafood',
    39.8,
    '200g',
    'salmon',
    '建议充分加热后食用，可香煎或烤制',
    ['鱼类', '香煎'],
    ['三文鱼', '鲑鱼', 'salmon'],
  ],
  [
    'carp',
    '鲜活草鱼',
    'seafood',
    12.8,
    '500g',
    'fish',
    '适合炖汤、红烧，烹饪前注意鱼刺',
    ['鱼类', '红烧'],
    ['草鱼', 'carp'],
  ],
  [
    'shrimp',
    '鲜白对虾',
    'seafood',
    29.8,
    '500g',
    'shrimp',
    '白灼、油焖都能吃到鲜甜滋味',
    ['虾类'],
    ['虾', '对虾', '虾仁', 'shrimp'],
  ],
  [
    'chicken',
    '去皮鸡胸肉',
    'meat',
    13.8,
    '500g',
    'chicken',
    '适合煎烤、凉拌，烹饪时充分加热',
    ['鸡肉', '家常'],
    ['鸡胸', '鸡肉', 'chicken'],
  ],
  [
    'pork',
    '冷鲜猪里脊',
    'meat',
    19.8,
    '500g',
    'pork',
    '肉质细嫩，切丝快炒很合适',
    ['猪肉'],
    ['猪肉', '里脊', 'pork'],
  ],
  [
    'beef',
    '原切牛排',
    'meat',
    39.9,
    '200g',
    'beef',
    '原切肉质，适合平底锅香煎',
    ['牛肉'],
    ['牛肉', '牛排', 'beef'],
  ],
  [
    'milk',
    '牧场纯牛奶',
    'dairy',
    12.9,
    '1L',
    'milk',
    '早餐搭配，请按包装要求冷藏',
    ['牛奶'],
    ['纯牛奶', '牛奶', 'milk'],
  ],
  [
    'yogurt',
    '原味酸奶',
    'dairy',
    6.9,
    '200g',
    'yogurt',
    '原味发酵乳，冷藏后口感更佳',
    ['酸奶'],
    ['酸奶', 'yogurt'],
  ],
  [
    'egg',
    '新鲜鸡蛋',
    'dairy',
    9.9,
    '6枚',
    'egg',
    '早餐常备，水煮或煎炒皆宜',
    ['禽蛋'],
    ['鸡蛋', '蛋', 'egg'],
  ],
  [
    'bread',
    '全麦吐司',
    'bakery',
    12.8,
    '400g',
    'bread',
    '麦香浓郁，适合做三明治',
    ['面包', '早餐'],
    ['吐司', '面包', 'bread'],
  ],
  [
    'croissant',
    '黄油可颂',
    'bakery',
    8.8,
    '个',
    'croissant',
    '层层酥香，稍加复烤更松脆',
    ['面包'],
    ['可颂', '牛角包', 'croissant'],
  ],
  [
    'rice',
    '东北珍珠米',
    'pantry',
    29.9,
    '2.5kg',
    'rice',
    '米粒饱满，适合日常煮饭',
    ['主食'],
    ['大米', '米', 'rice'],
  ],
  [
    'oil',
    '压榨菜籽油',
    'pantry',
    39.9,
    '1.8L',
    'oil',
    '适合日常煎炒，阴凉干燥处存放',
    ['食用油'],
    ['菜籽油', '食用油', '油', 'oil'],
  ],
  ['salt', '加碘食用盐', 'pantry', 2.5, '400g', 'rice', '基础调味，按需少量使用', ['调味'], ['食盐', '盐']],
  ['sugar', '白砂糖', 'pantry', 5.9, '400g', 'rice', '烹饪调味用糖', ['调味'], ['白糖', '糖']],
  ['soy-sauce', '生抽', 'pantry', 8.9, '500ml', 'rice', '咸鲜调味，开封后按包装要求保存', ['调味'], ['酱油', '生抽']],
  ['dark-soy', '老抽', 'pantry', 9.9, '500ml', 'rice', '上色调味，少量使用', ['调味'], ['老抽']],
  ['vinegar', '米醋', 'pantry', 6.9, '500ml', 'rice', '酸味调料', ['调味'], ['醋', '米醋', '香醋']],
  ['cooking-wine', '料酒', 'pantry', 8.9, '500ml', 'rice', '烹饪去腥调料', ['调味'], ['料酒']],
  ['char-siu-sauce', '叉烧酱', 'pantry', 12.9, '250g', 'rice', '特色调味酱料', ['特色调味'], ['叉烧酱']],
  ['red-fermented-tofu', '红腐乳', 'pantry', 7.9, '340g', 'rice', '特色发酵调味品', ['特色调味'], ['红腐乳', '腐乳']],
  ['rose-wine', '玫瑰露酒', 'pantry', 18.9, '300ml', 'rice', '特色烹饪酒', ['特色调味'], ['玫瑰露酒']],
  ['ginger', '生姜', 'vegetables', 3.9, '250g', 'bokchoy', '葱姜蒜等鲜料，按需购买', ['鲜料'], ['姜', '生姜']],
  ['scallion', '小葱', 'vegetables', 2.9, '100g', 'bokchoy', '葱姜蒜等鲜料，按需购买', ['鲜料'], ['葱', '小葱', '大葱']],
  ['garlic', '大蒜', 'vegetables', 3.5, '200g', 'bokchoy', '葱姜蒜等鲜料，按需购买', ['鲜料'], ['蒜', '大蒜']],
  ['chili', '鲜辣椒', 'vegetables', 4.8, '200g', 'tomato', '鲜辣椒，按菜谱用量购买', ['鲜料'], ['辣椒', '小米辣', '青椒']],
  ['onion', '洋葱', 'vegetables', 4.5, '500g', 'tomato', '可用于炒菜和炖菜', ['蔬菜'], ['洋葱']],
  ['tofu', '北豆腐', 'dairy', 4.9, '400g', 'milk', '豆制品，冷藏保存', ['豆制品'], ['豆腐', '北豆腐', '豆制品']],
  ['oats', '即食燕麦片', 'pantry', 12.9, '500g', 'rice', '早餐主食，可按包装说明冲泡', ['主食'], ['燕麦', '燕麦片']],
  ['noodles', '挂面', 'pantry', 5.9, '500g', 'rice', '日常主食', ['主食'], ['面条', '挂面']],
  ['black-pepper', '黑胡椒粉', 'pantry', 8.9, '30g', 'rice', '香料调味，按菜谱用量购买', ['香料'], ['黑胡椒', '胡椒粉']],
  ['cumin', '孜然粉', 'pantry', 7.9, '30g', 'rice', '香料调味，按菜谱用量购买', ['香料'], ['孜然', '孜然粉']],
  ['toilet-paper', '卷纸', 'home', 16.9, '10卷', 'market', '家庭日用品（演示商品）', ['日用'], ['卷纸', '卫生纸']],
  ['laundry-detergent', '洗衣液', 'cleaning', 22.9, '1L', 'market', '日用清洁（演示商品）', ['清洁'], ['洗衣液']],
];

export function makeSeedProducts(): Product[] {
  const now = new Date();
  const date = (ago: number) => new Date(now.getTime() - ago * 86400000).toISOString().slice(0, 10);
  return definitions.map(
    ([id, name, category, price, unit, image, description, tags, aliases], index) => ({
      id,
      name,
      category,
      price,
      unit,
      image: `/images/${image}.jpg`,
      description,
      tags,
      aliases,
      stock: 32 + ((index * 13) % 88),
      shelf: `${(zones.find((z) => z.id === category) || zones.find((z) => z.id === 'pantry')!).code}-${String((index % 3) + 1).padStart(2, '0')}`,
      shelfId: `${(zones.find((z) => z.id === category) || zones.find((z) => z.id === 'pantry')!).id}-shelf-01`,
      saleMode:
        ['spinach', 'bokchoy', 'lettuce', 'broccoli', 'tomato', 'carrot', 'apple', 'banana', 'orange', 'seabass', 'carp', 'shrimp', 'chicken', 'pork', 'ginger', 'scallion', 'garlic', 'onion', 'chili'].includes(id)
          ? 'weight'
          : 'pack',
      packageSize: inferPackageSize({ unit } as Product),
      history: [0.94, 1.04, 0.98, 1.02, 1].map((factor, i) => ({
        price: Math.round(price * factor * 10) / 10,
        date: date(28 - i * 6),
        source: 'seed',
      })),
      marketPrice: Math.round(price * 1.06 * 10) / 10,
      marketDate: date(0),
      marketSource: '演示参考价（非实时行情）',
      createdAt: now.toISOString(),
    }),
  );
}

export const visionLabels: {
  name: string;
  category: Category;
  english: string;
  productId: string;
}[] = [
  { name: '菠菜', category: 'vegetables', english: 'fresh spinach leaves', productId: 'spinach' },
  {
    name: '上海青',
    category: 'vegetables',
    english: 'fresh bok choy pak choi cabbage',
    productId: 'bokchoy',
  },
  { name: '生菜', category: 'vegetables', english: 'fresh lettuce', productId: 'lettuce' },
  { name: '西兰花', category: 'vegetables', english: 'fresh broccoli', productId: 'broccoli' },
  { name: '番茄', category: 'vegetables', english: 'red tomatoes', productId: 'tomato' },
  { name: '胡萝卜', category: 'vegetables', english: 'orange carrots', productId: 'carrot' },
  { name: '苹果', category: 'fruit', english: 'red apples', productId: 'apple' },
  { name: '香蕉', category: 'fruit', english: 'yellow bananas', productId: 'banana' },
  { name: '橙子', category: 'fruit', english: 'oranges fruit', productId: 'orange' },
  { name: '草莓', category: 'fruit', english: 'red strawberries', productId: 'strawberry' },
  { name: '鲜鱼', category: 'seafood', english: 'a whole raw fresh fish', productId: 'seabass' },
  { name: '三文鱼', category: 'seafood', english: 'a raw salmon fillet', productId: 'salmon' },
  { name: '鲜虾', category: 'seafood', english: 'raw shrimp prawns', productId: 'shrimp' },
  { name: '鸡胸肉', category: 'meat', english: 'raw chicken breast', productId: 'chicken' },
  { name: '猪肉', category: 'meat', english: 'raw pork meat', productId: 'pork' },
  { name: '牛肉', category: 'meat', english: 'raw beef steak', productId: 'beef' },
  { name: '牛奶', category: 'dairy', english: 'a milk bottle or carton', productId: 'milk' },
  { name: '酸奶', category: 'dairy', english: 'a cup of yogurt', productId: 'yogurt' },
  { name: '鸡蛋', category: 'dairy', english: 'chicken eggs', productId: 'egg' },
  { name: '面包', category: 'bakery', english: 'sliced bread toast', productId: 'bread' },
  { name: '可颂', category: 'bakery', english: 'a croissant pastry', productId: 'croissant' },
  { name: '大米', category: 'pantry', english: 'white rice grains', productId: 'rice' },
  { name: '食用油', category: 'pantry', english: 'a bottle of cooking oil', productId: 'oil' },
];
